name: Backend heroku

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: git push https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/ppleague-backend.git master:master
