name: Backend heroku

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Make jar directory
      run: mkdir jar
    - name: Copy jar
      run: cp target/*.jar jar/
    - name: Install build plugin
      uses: actions/heroku@1.0.0
      with:
        args: "plugins:install heroku-builds"
    - name: Change dir
      run: cd jar
    - name: Deploy jar to heroku
      uses: actions/heroku@1.0.0
      with:
        args: "builds:create -a ppleague_backend"
        secrets: ${{ secrets.HEROKU_API_TOKEN }}
