name: Frontend

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to heroku
      uses: actions/heroku@1.0.0
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      with:
        args: "container:login"
        secrets: ${{ secrets.HEROKU_API_TOKEN }}
    - name: Install build plugin #
      uses: actions/heroku@1.0.0
      with:
        args: "plugins:install heroku-builds"
    - name: Change dir
      run: cd src/web
    - name: Deploy jar to heroku
      uses: actions/heroku@1.0.0
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      with:
        args: "builds:create -a pp-league"
        secrets: ${{ secrets.HEROKU_API_TOKEN }}
      
      
    
